service: alg-opsbot
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  deploymentBucket:
    name: alg-ops
  region: eu-west-3
  logRetentionInDays: 14
  stackName: alg-opsbot

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'lambda:GetAlias'
            - 'lambda:UpdateAlias'
            - 'lambda:ListVersionsByFunction'
          Resource: "*"
        - Effect: Allow
          Action: 'lambda:InvokeFunction'
          Resource:
            - arn:aws:lambda:eu-west-3:565617039749:function:alg-backend-*-command
  
  runtime: nodejs18.x
  memorySize: 128

  environment: 
    STAGE: ${opt:stage, 'dev'}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    SKIP_SIGNATURE_CHECK: ${env:SKIP_SIGNATURE_CHECK}
    SLACK_SUPERUSERS: ${env:SLACK_SUPERUSERS}
    CIRCLECI_TOKEN: ${env:CIRCLECI_TOKEN}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}
    DEBUG: ${env:DEBUG}

functions:
  slackbot:
    handler: src/handlers/bot.streamHandler
    name: alg-opsbot-slackbot
    url:
      invokeMode: RESPONSE_STREAM
    timeout: 60 # it needs to responds in <3sec to Slack, but then it can still do processing
    reservedConcurrency: 1

  warmer:
    handler: src/handlers/warmer.handler
    name: alg-opsbot-warmer
    timeout: 15
    events:
      - schedule:
          rate: rate(5 minutes)
          input:
            urls:
              - https://beta.parcours.algorea.org/en/
              - https://beta.parcours.algorea.org/api/
              - https://74w4cx6w62uon4dtqinf6quqeu0qvunw.lambda-url.eu-west-3.on.aws/ # search
              - https://awc2x5cps5hkakahhove6uqhyu0tffzi.lambda-url.eu-west-3.on.aws/ # propagation end-point
              - https://mhwyddf7lsgoallzunpeuaj5fi0gnaex.lambda-url.eu-west-3.on.aws/ # slack bot

package: 
  individually: true

plugins:
  - serverless-plugin-typescript
