
frontend:
  deployment_id: 59
  version: 2.27.0
  config_file: default-frontend.ts
  deployment_prefix: default
  build_fr: true

backend:
  deployment_id: 13
  version: 1.7.0
  config_file: default-backend.yml
  public_key_file: default-public.pem
  private_key_file: default-private.pem
  lambda_env_file: default-algoreabackend-lambda.json
  migration_secrets_file: default-migration-secrets.yml
