
frontend:
  deployment_id: 84
  version: 2.39.4
  config_file: default-frontend.ts
  deployment_prefix: default
  build_fr: true

backend:
  deployment_id: 29
  version: 2.14.2
  config_file: default-backend.yml
  public_key_file: default-public.pem
  private_key_file: default-private.pem
  lambda_env_file: default-algoreabackend-lambda.json
  migration_secrets_file: default-migration-secrets.yml
