
frontend:
  deployment_id: 26
  version: 1.10.2
  config_file: default-frontend.ts
  deployment_prefix: default

backend:
  deployment_id: 6
  version: 1.2.0
  config_file: default-backend.yml
  public_key_file: default-public.pem
  private_key_file: default-private.pem
  lambda_env_file: default-algoreabackend-lambda.json
  migration_secrets_file: default-migration-secrets.yml
