
frontend:
  deployment_id: 61
  version: 2.28.1
  config_file: default-frontend.ts
  deployment_prefix: default
  build_fr: true

backend:
  deployment_id: 21
  version: 1.9.3
  config_file: default-backend.yml
  public_key_file: default-public.pem
  private_key_file: default-private.pem
  lambda_env_file: default-algoreabackend-lambda.json
  migration_secrets_file: default-migration-secrets.yml
