
frontend:
  deployment_id: 69
  version: 2.34.0
  config_file: default-frontend.ts
  deployment_prefix: default
  build_fr: true

backend:
  deployment_id: 24
  version: 1.12.0
  config_file: default-backend.yml
  public_key_file: default-public.pem
  private_key_file: default-private.pem
  lambda_env_file: default-algoreabackend-lambda.json
  migration_secrets_file: default-migration-secrets.yml
