version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  frontend-deploy:
    working_directory: /home/circleci/project
    docker:
      - image: cimg/node:16.20
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1
      - run: ./scripts/decrypt.sh environments/frontend
      - run: ./scripts/frontend-deploy.sh

  backend-deploy:
    docker:
      - image: cimg/node:16.20
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1
      - run: ./scripts/decrypt.sh environments/backend
      - run: ./scripts/backend-deploy.sh

workflows:
  version: 2
  default:
    jobs:
      - frontend-deploy
      - backend-deploy