version: 2.1

parameters:
  deploy-app:
    type: enum
    enum: ["auto", "frontend", "backend"]
    default: auto
  deploy-env:
    type: string
    default: ""
  deploy-version:
    type: string
    default: ""
  deploy-app-config:
    type: string
    default: ""

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  slack: circleci/slack@4.9.3

jobs:
  frontend-deploy:
    working_directory: /home/circleci/project
    docker:
      - image: cimg/node:18.13
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1 serverless-prune-plugin@2.0.2
      - run: ./scripts/get-config.sh ./config frontend << pipeline.parameters.deploy-env >> << pipeline.parameters.deploy-app-config >>
      - run: ./scripts/decrypt.sh ./config
      - run: ./scripts/frontend-deploy.sh << pipeline.parameters.deploy-env >> << pipeline.parameters.deploy-version >> ./config
      - slack/notify:
          channel: algoreaops-bot
          event: pass
          custom: |
              {
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "plain_text",
                        "text": "${OUTPUTMSG}",
                        "emoji": true
                      }
                    ],
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Release now 🚀",
                        "emoji": true
                      },
                      "value": "release frontend << pipeline.parameters.deploy-env >> ${DEPLOYED_VERSION}",
                      "action_id": "command"
                    }
                  }
                ]
              }
      - slack/notify:
          channel: algoreaops-bot
          event: fail
          custom: |
              {
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "plain_text",
                        "text": "Error on frontend deployment << pipeline.parameters.deploy-env >> << pipeline.parameters.deploy-version >> << pipeline.parameters.deploy-app-config >>",
                        "emoji": true
                      }
                    ]
                  }
                ]
              }
  backend-deploy:
    docker:
      - image: cimg/node:16.20
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1 serverless-prune-plugin@2.0.2
      - run: ./scripts/get-config.sh ./config backend << pipeline.parameters.deploy-env >> << pipeline.parameters.deploy-app-config >>
      - run: ./scripts/decrypt.sh ./config
      - run: ./scripts/backend-deploy.sh << pipeline.parameters.deploy-env >> << pipeline.parameters.deploy-version >> ./config
      - slack/notify:
          channel: algoreaops-bot
          event: pass
          custom: |
              {
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "plain_text",
                        "text": "${OUTPUTMSG}",
                        "emoji": true
                      }
                    ],
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Release now 🚀",
                        "emoji": true
                      },
                      "value": "release backend << pipeline.parameters.deploy-env >> ${DEPLOYED_VERSION}",
                      "action_id": "command"
                    }
                  }
                ]
              }
      - slack/notify:
          channel: algoreaops-bot
          event: fail
          custom: |
              {
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "plain_text",
                        "text": "Error on backend deployment << pipeline.parameters.deploy-env >> << pipeline.parameters.deploy-version >> << pipeline.parameters.deploy-app-config >>",
                        "emoji": true
                      }
                    ]
                  }
                ]
              }
  forum-deploy:
    docker:
      - image: cimg/node:16.20
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1
      - run: ./scripts/forum-deploy.sh

  search-deploy:
    docker:
      - image: cimg/node:16.20
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1
      - run: ./scripts/decrypt.sh environments/search
      - run: ./scripts/search-deploy.sh

  opsbot-deploy:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1
      - run: ./scripts/decrypt.sh environments/opsbot
      - run: ./scripts/opsbot-deploy.sh

workflows:
  version: 2
  default:
    when:
      equal: [ auto, << pipeline.parameters.deploy-app >> ]
    jobs:
      - forum-deploy
      - search-deploy
      - opsbot-deploy
  frontend:
    when:
      equal: [ frontend, << pipeline.parameters.deploy-app >> ]
    jobs:
      - frontend-deploy:
          context: slack-secrets
  backend:
    when:
      equal: [ backend, << pipeline.parameters.deploy-app >> ]
    jobs:
      - backend-deploy:
          context: slack-secrets
