version: 2.1

parameters:
  deploy-app:
    type: enum
    enum: ["auto", "frontend", "backend"]
    default: auto
  deploy-env:
    type: string
    default: ""
  deploy-version:
    type: string
    default: ""
  deploy-app-config:
    type: string
    default: ""

orbs:
  aws-s3: circleci/aws-s3@1.0.15
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  frontend-deploy:
    working_directory: /home/circleci/project
    docker:
      - image: cimg/node:18.13
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1
      - run: ./scripts/get-config.sh ./config frontend << pipeline.parameters.deploy-env >> << pipeline.parameters.deploy-app-config >>
      - run: ./scripts/decrypt.sh ./config
      - run: ./scripts/frontend-deploy.sh << pipeline.parameters.deploy-env >> << pipeline.parameters.deploy-version >> ./config

  backend-deploy:
    docker:
      - image: cimg/node:16.20
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1
      - run: ./scripts/get-config.sh ./config backend << pipeline.parameters.deploy-env >> << pipeline.parameters.deploy-app-config >>
      - run: ./scripts/decrypt.sh ./config
      - run: ./scripts/backend-deploy.sh << pipeline.parameters.deploy-env >> << pipeline.parameters.deploy-version >> ./config

  forum-deploy:
    docker:
      - image: cimg/node:16.20
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1
      - run: ./scripts/forum-deploy.sh

  search-deploy:
    docker:
      - image: cimg/node:16.20
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1
      - run: ./scripts/decrypt.sh environments/search
      - run: ./scripts/search-deploy.sh

  opsbot-deploy:
    docker:
      - image: cimg/node:16.20
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: npm install -g serverless@3.30.1
      - run: ./scripts/decrypt.sh environments/opsbot
      - run: ./scripts/opsbot-deploy.sh

workflows:
  version: 2
  default:
    when:
      equal: [ auto, << pipeline.parameters.deploy-app >> ]
    jobs:
      - forum-deploy
      - search-deploy
      - opsbot-deploy
  frontend:
    when:
      equal: [ frontend, << pipeline.parameters.deploy-app >> ]
    jobs:
      - frontend-deploy
  backend:
    when:
      equal: [ backend, << pipeline.parameters.deploy-app >> ]
    jobs:
      - backend-deploy
