service: alg-backend-propagation
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  deploymentBucket:
    name: ${env:OPS_BUCKET}
  runtime: nodejs18.x
  region: eu-west-3
  logRetentionInDays: 90
  environment:
    STAGE: ${opt:stage, 'dev'}
    DISABLE: ${env:DISABLE, ''}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: lambda:InvokeFunction
          Resource:
            - arn:aws:lambda:eu-west-3:*:function:alg-backend-${opt:stage}-command

package:
  individually: true

functions:

  propagate:
    name: alg-backend-propagation-${opt:stage}
    handler: src/propagation.streamHandler
    url:
      invokeMode: RESPONSE_STREAM
    timeout: 5

plugins:
  - serverless-plugin-typescript
