service: alg-frontend
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  deploymentBucket:
    name: alg-ops
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:GetObject'
          Resource:
            - arn:aws:s3:::${env:S3_BUCKET}/deployments/${opt:stage, 'dev'}/*
  runtime: nodejs18.x
  region: eu-west-3
  logRetentionInDays: 90
  environment:
    STAGE: ${opt:stage, 'dev'}
    DEBUG: ${env:DEBUG}
    NO_CACHE: ${env:NO_CACHE}
    S3_BUCKET: ${env:S3_BUCKET}
    S3_PREFIX: ${env:S3_PREFIX}
    S3_REGION: ${env:S3_REGION}

package:
  patterns:
    - '!**'
    - index.js
    
functions:
  static-serve:
    handler: index.handler
    timeout: 3
    memorySize: 1024
    description: ${param:description}
