service: alg-backend
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  deploymentBucket:
    name: alg-ops
  runtime: provided.al2
  region: eu-west-3
  logRetentionInDays: 90
  environment:
    STAGE: ${opt:stage, 'dev'}
    ALGOREA_ENV: ${env:ALGOREA_ENV}
    ALGOREA_TOKEN__PLATFORMNAME: ${env:ALGOREA_TOKEN__PLATFORMNAME}
    ALGOREA_LOGGING__LOGRAWSQLQUERIES: ${env:ALGOREA_LOGGING__LOGRAWSQLQUERIES}
    ALGOREA_LOGGING__LOGSQLQUERIES: ${env:ALGOREA_LOGGING__LOGSQLQUERIES}
    ALGOREA_AUTH__CLIENTID: ${env:ALGOREA_AUTH__CLIENTID}
    ALGOREA_AUTH__CLIENTSECRET: ${env:ALGOREA_AUTH__CLIENTSECRET}
    ALGOREA_DATABASE__USER: ${env:ALGOREA_DATABASE__USER}
    ALGOREA_DATABASE__PASSWD: ${env:ALGOREA_DATABASE__PASSWD}
    ALGOREA_DATABASE__ADDR: ${env:ALGOREA_DATABASE__ADDR}
    ALGOREA_DATABASE__DBNAME: ${env:ALGOREA_DATABASE__DBNAME}

package:
  individually: true

functions:
  server:
    handler: bootstrap
    package:
      artifact: build/server.zip
    timeout: 15
    memorySize: 2064

  command:
    handler: bootstrap
    environment:
      ALGOREA_DATABASE__USER: ${env:ALGOREA_DATABASE__ADMINUSER}
      ALGOREA_DATABASE__PASSWD: ${env:ALGOREA_DATABASE__ADMINPASSWD}
    package:
      artifact: build/command.zip
    timeout: 900
    memorySize: 2064
